{% set name = "xeus-lua" %}
{% set version = "0.4.1" %}
{% set sha256 = "5ceaa39178f26d2207c72cb4c7ce02b07db90b87d8218bbe3f73eed589ae3f33" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://github.com/jupyter-xeus/xeus-lua/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
  host:
    - cppzmq >=4.6.0,<5
    - zeromq
    - openlibm  # [linux]
    - lua >=5.2.0
    - xeus >=2.0
    - xtl >=0.7
    - xwidgets >=0.25.1

test:
  commands:
    - test -f ${PREFIX}/bin/xlua                                                            # [unix]
    - test -f ${PREFIX}/share/jupyter/kernels/xlua/kernel.json                              # [unix]
    - if not exist %LIBRARY_BIN%\\xlua.exe (exit 1)                                         # [win]
    - if not exist %LIBRARY_PREFIX%\\share\\jupyter\\kernels\\xlua\\kernel.json (exit 1)    # [win]
    - test -d ${PREFIX}/include/xeus-lua                                                    # [unix]
    - test -f ${PREFIX}/include/xeus-lua/xinterpreter.hpp                                   # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-lua/xeus-luaConfig.cmake                             # [unix]
    - test -f ${PREFIX}/lib/cmake/xeus-lua/xeus-luaConfigVersion.cmake                      # [unix]
    - if not exist %LIBRARY_INC%\\xeus-lua\\xinterpreter.hpp (exit 1)                       # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\xeus-lua\\xeus-luaConfig.cmake (exit 1)            # [win]
    - if not exist %LIBRARY_LIB%\\cmake\\xeus-lua\\xeus-luaConfigVersion.cmake (exit 1)     # [win]
    # The kernel spec in installed in the general PREFIX
    - if not exist %PREFIX%\\share\\jupyter\\kernels\\xlua\\kernel.json (exit 1)            # [win]

about:
  home: https://github.com/jupyter-xeus/xeus-lua
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Lua kernel for Jupyter based on xeus
  description: Jupyter kernel for the Lua programming language
  doc_url: https://xeus-lua.readthedocs.io
  dev_url: https://github.com/jupyter-xeus/xeus-lua

extra:
  recipe-maintainers:
    - DerThorsten
